# Generated by Django 5.1.1 on 2024-11-13 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False, verbose_name='game_id')),
                ('game_name', models.CharField(max_length=200, verbose_name='game_name')),
                ('stock_nb', models.IntegerField(blank=True, default=1, verbose_name='stock_nb')),
                ('game_length_min', models.IntegerField(blank=True, default=0, verbose_name='game_length_min')),
                ('game_length_max', models.IntegerField(blank=True, default=999, verbose_name='game_length_max')),
                ('min_players', models.IntegerField(blank=True, default=1, verbose_name='min_players')),
                ('max_players', models.IntegerField(blank=True, default=99, verbose_name='max_players')),
                ('min_age', models.IntegerField(blank=True, default=0, verbose_name='min_age')),
            ],
        ),
        migrations.CreateModel(
            name='Extensions',
            fields=[
                ('extension_id', models.AutoField(primary_key=True, serialize=False, verbose_name='extension_id')),
                ('time_add', models.IntegerField(verbose_name='time_add')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_games.games')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('play_id', models.AutoField(primary_key=True, serialize=False, verbose_name='play_id')),
                ('date', models.DateField(verbose_name='date')),
                ('rating', models.IntegerField(blank=True, verbose_name='rating')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_games.games')),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('lending_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField(verbose_name='date_start')),
                ('date_expected_end', models.DateField(verbose_name='date_end')),
                ('date_end', models.DateField(blank=True, verbose_name='date_end')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_games.games')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History_players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_games.history')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('play_id', 'user_id'), name='unique_migration_host_combination_history')],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=200, verbose_name='tag_id')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_games.games')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game_id', 'tag_id'), name='unique_migration_host_combination_tags')],
            },
        ),
    ]
