# Generated by Django 5.1.1 on 2024-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extensions',
            fields=[
                ('extension_id', models.AutoField(primary_key=True, serialize=False, verbose_name='extension_id')),
                ('game_id', models.IntegerField(verbose_name='game_id')),
                ('time_add', models.IntegerField(verbose_name='time_add')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False, verbose_name='game_id')),
                ('game_name', models.CharField(max_length=200, verbose_name='game_name')),
                ('stock_nb', models.IntegerField(blank=True, default=0, verbose_name='stock_nb')),
                ('game_length_min', models.IntegerField(blank=True, default=0, verbose_name='game_length_min')),
                ('game_length_max', models.IntegerField(blank=True, default=999, verbose_name='game_length_max')),
                ('min_players', models.IntegerField(blank=True, default=0, verbose_name='min_players')),
                ('max_players', models.IntegerField(blank=True, default=0, verbose_name='max_players')),
                ('min_age', models.IntegerField(blank=True, default=0, verbose_name='min_age')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('play_id', models.AutoField(primary_key=True, serialize=False, verbose_name='play_id')),
                ('game_id', models.IntegerField(verbose_name='game_id')),
                ('date', models.DateField(verbose_name='date')),
                ('rating', models.IntegerField(blank=True, verbose_name='rating')),
            ],
        ),
        migrations.CreateModel(
            name='History_players',
            fields=[
                ('play_id', models.AutoField(primary_key=True, serialize=False, verbose_name='play_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('lending_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('game_id', models.IntegerField(verbose_name='game_id')),
                ('date_start', models.DateField(verbose_name='date_start')),
                ('date_expected_end', models.DateField(verbose_name='date_end')),
                ('date_end', models.DateField(blank=True, verbose_name='date_end')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False, verbose_name='game_id')),
                ('tag_id', models.CharField(max_length=200, verbose_name='tag_id')),
            ],
        ),
    ]
