# Generated by Django 5.1.1 on 2024-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='max_players',
            field=models.IntegerField(blank=True, default=99, verbose_name='max_players'),
        ),
        migrations.AlterField(
            model_name='games',
            name='min_players',
            field=models.IntegerField(blank=True, default=1, verbose_name='min_players'),
        ),
        migrations.AlterField(
            model_name='games',
            name='stock_nb',
            field=models.IntegerField(blank=True, default=1, verbose_name='stock_nb'),
        ),
    ]
