# Generated by Django 5.1.1 on 2024-11-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensions',
            name='extension_name',
            field=models.CharField(default='Sans nom', max_length=200, unique=True, verbose_name='extension_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='game_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='game_name'),
        ),
    ]
