# Generated by Django 5.1.1 on 2024-11-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0002_extensions_extension_name_alter_games_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='date_end'),
        ),
    ]
