# Generated by Django 5.1.1 on 2024-11-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0002_alter_games_max_players_alter_games_min_players_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='history_players',
            constraint=models.UniqueConstraint(fields=('play_id', 'user_id'), name='unique_migration_host_combination_history'),
        ),
        migrations.AddConstraint(
            model_name='tags',
            constraint=models.UniqueConstraint(fields=('game_id', 'tag_id'), name='unique_migration_host_combination_tags'),
        ),
    ]
