name: Code Coverage

on:
  pull_request:
  push:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install codecov

      - name: Run tests and collect coverage
        run: |
          cd website
          coverage run manage.py test
          coverage xml -o coverage.xml
          coverage report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: website/coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
